# Generated by Django 3.2.16 on 2023-01-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description',
            new_name='desc',
        ),
    ]
