# Generated by Django 3.2.16 on 2023-01-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_superheros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superheros',
            old_name='name',
            new_name='names',
        ),
    ]
